- name: Create Folder
  community.general.jenkins_jobs:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.2.12:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: Include Multi Branch Pipeline Jobs File
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Include Single Pipeline Jobs File
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"

