- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml


- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    url: http://172.31.2.12:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend
    - cart
    - catalogue
