- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/folder.xml


- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.2.12:8080
    user: admin
    password: "{{jenkins_password}}"


- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml


- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/{{item}}.xml') }}"
    name: "{{item.dir}}//{{item.name}}"
    url: http://172.31.2.12:8080
    user: admin
    password: "{{jenkins_password}}"